[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
aegis = "Hs2JZNwdk6QqMWPkipSe513qLQVQH8EWkU2w8N2vgLUw"
aegis_hook = "PHoRUD1bk52nZmdkQ2qGTjMx71wKDM8bEzfeACzFXk5"
aegis_faucet = "GYsrUAn1S12UCNG4a212HYyvvhQiUdyva1PJbyaZdcLU"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[hooks]
